-- =====================================================================
-- SEED: Centros de salud de Managua (ciudad) -- Fuente: dataset MINSA
-- provisto por el usuario, con columnas silais/distrito realineadas
-- (ver hallazgo de desalineación en la respuesta de la auditoría).
-- 66 registros, filtrados a municipio = 'Managua' (capital), tal como
-- se pidió explícitamente ('solo enfocado en Managua, Managua').
--
-- Requiere migrations/005_centros_salud_recomendador.sql aplicado antes.
-- Ejecutar una sola vez por entorno: la tabla no tiene una restricción
-- UNIQUE para nombre+latitud+longitud y repetir este archivo duplicaría filas.
-- =====================================================================

BEGIN;

INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Hospital Antonio Lenín Fonseca', 'HOSPITAL', 'Hospital Referencia Nacional', 'MANAGUA', 'D2', 'Managua', 'Reparto Los Arcos', 'Urbano', ARRAY['Multiespecialidad','Alta tecnología','Cirugía','Medicina interna']::text[], 12.14867, -86.31176, 'Reparto Los Arcos', true);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Hospital de Rehabilitación Aldo Chavarría', 'HOSPITAL', 'Hospital Referencia Nacional', 'MANAGUA', 'D2', 'Managua', 'Contiguo a Enacal Central Batahola Norte', 'Urbano', ARRAY['Rehabilitación física','Medicina física']::text[], 12.13850, -86.30750, 'Contiguo a Enacal Central Batahola Norte', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Centro Nacional Dermatológico Francisco Urcuyo', 'HOSPITAL', 'Hospital Referencia Nacional', 'MANAGUA', 'D2', 'Managua', 'Estatua Monseñor Lezcano 1 al Sur 1 abajo', 'Urbano', ARRAY['Dermatología']::text[], 12.13500, -86.30500, 'Estatua Monseñor Lezcano 1 al Sur 1 abajo', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Hospital Nacional CENAO (Centro Nacional de Oftalmología)', 'HOSPITAL', 'Hospital Referencia Nacional', 'MANAGUA', 'D2', 'Managua', 'Frente al cementerio San Pedro Boer', 'Urbano', ARRAY['Oftalmología','Cirugía ocular']::text[], 12.13600, -86.30900, 'Frente al cementerio San Pedro Boer', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Hospital Psicosocial (José Dolores Fletes)', 'HOSPITAL', 'Hospital Referencia Nacional', 'MANAGUA', 'D2', 'Managua', 'Enacal Central 1c al sur Batahola Norte', 'Urbano', ARRAY['Psiquiatría','Salud mental']::text[], 12.13827, -86.30821, 'Enacal Central 1c al sur Batahola Norte', true);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Hospital Bertha Calderón Roque', 'HOSPITAL', 'Hospital Referencia Nacional', 'MANAGUA', 'D3', 'Managua', 'Frente a INATEC Centro Cívico Héroes y Mártires del Bocay', 'Urbano', ARRAY['Gineco-obstetricia','Salud de la mujer','Maternidad']::text[], 12.12421, -86.29854, 'Frente a INATEC Centro Cívico Héroes y Mártires del Bocay', true);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Hospital Fernando Vélez Paiz', 'HOSPITAL', 'Hospital Referencia Nacional', 'MANAGUA', 'D3', 'Managua', 'Del Banco Central de Nicaragua 1c arriba Tierra Prometida', 'Urbano', ARRAY['Multiespecialidad','Salud del hombre','Cirugía']::text[], 12.12127, -86.30619, 'Del Banco Central de Nicaragua 1c arriba Tierra Prometida', true);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Hospital Nacional de Radioterapia Nora Astorga', 'HOSPITAL', 'Hospital Referencia Nacional', 'MANAGUA', 'D3', 'Managua', 'De donde fue el Juzgado Nacional 2½ c al sur Tierra Prometida', 'Urbano', ARRAY['Oncología','Radioterapia']::text[], 12.12000, -86.30700, 'De donde fue el Juzgado Nacional 2½ c al sur Tierra Prometida', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Hospital Solidaridad', 'HOSPITAL', 'Hospital Referencia Nacional', 'MANAGUA', 'D4', 'Managua', 'De donde fue la Pepsi 2c al sur Barrio Los Angeles', 'Urbano', ARRAY['Multiespecialidad']::text[], 12.11800, -86.29500, 'De donde fue la Pepsi 2c al sur Barrio Los Angeles', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Hospital Infantil Manuel de Jesús Rivera La Mascota', 'HOSPITAL', 'Hospital Referencia Nacional', 'MANAGUA', 'D5', 'Managua', 'Bo Ariel Darce Distrito V', 'Urbano', ARRAY['Pediatría','Neonatología','Cirugía pediátrica']::text[], 12.12410, -86.23588, 'Bo Ariel Darce Distrito V', true);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Hospital Manolo Morales Peralta', 'HOSPITAL', 'Hospital Referencia Nacional', 'MANAGUA', 'D5', 'Managua', 'Frente al costado norte del mercado Roberto Huembes Isaías Gómez', 'Urbano', ARRAY['Multiespecialidad','Cirugía','Medicina interna']::text[], 12.12241, -86.24597, 'Frente al costado norte del mercado Roberto Huembes Isaías Gómez', true);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Hospital Departamental Alemán Nicaragüense', 'HOSPITAL', 'Hospital Departamental', NULL, NULL, 'Managua', 'Simens 2c al sur Bo Carlos Marx', 'Urbano', ARRAY['Multiespecialidad','Endoscopía']::text[], 12.13300, -86.28500, 'Simens 2c al sur Bo Carlos Marx', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Centro de Adicciones Benjamín Medina', 'CENTRO_SALUD', 'Centro Especializado', NULL, NULL, 'Managua', NULL, 'Urbano', ARRAY['Adicciones','Salud mental']::text[], 12.12500, -86.26000, NULL, false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Centro de Adicciones Valentín Méndez', 'CENTRO_SALUD', 'Centro Especializado', NULL, NULL, 'Managua', NULL, 'Urbano', ARRAY['Adicciones','Salud mental']::text[], 12.12800, -86.25500, NULL, false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Centro de Alta Tecnología - Hospital Antonio Lenin Fonseca', 'CENTRO_SALUD', 'Centro Especializado', NULL, NULL, 'Managua', NULL, 'Urbano', ARRAY['Diagnóstico por imagen','Alta tecnología']::text[], 12.14867, -86.31176, NULL, true);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Centro Nacional de Audiología y Logopedia Carlos Fonseca', 'CENTRO_SALUD', 'Centro Especializado', NULL, NULL, 'Managua', NULL, 'Urbano', ARRAY['Audiología','Logopedia']::text[], 12.13000, -86.28000, NULL, false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Centro Nacional de Cardiocirugía Pediátrico', 'CENTRO_SALUD', 'Centro Especializado', NULL, NULL, 'Managua', NULL, 'Urbano', ARRAY['Cardiología pediátrica','Cardiocirugía']::text[], 12.12410, -86.23588, NULL, true);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Centro Nacional de Cardiología', 'CENTRO_SALUD', 'Centro Especializado', NULL, NULL, 'Managua', NULL, 'Urbano', ARRAY['Cardiología','Hemodinamia']::text[], 12.12410, -86.23588, NULL, true);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Centro Nacional de Citología', 'CENTRO_SALUD', 'Centro Especializado', NULL, NULL, 'Managua', NULL, 'Urbano', ARRAY['Citología','Patología','Oncología']::text[], 12.13000, -86.27500, NULL, false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Centro Nacional de Diabetes Porfirio García', 'CENTRO_SALUD', 'Centro Especializado', NULL, NULL, 'Managua', NULL, 'Urbano', ARRAY['Endocrinología','Diabetes']::text[], 12.12500, -86.27000, NULL, false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Centro Nacional de Diagnóstico y Referencia (CNDR)', 'CENTRO_SALUD', 'Centro Especializado', NULL, NULL, 'Managua', NULL, 'Urbano', ARRAY['Radiología','Tomografía','Resonancia magnética','Laboratorio']::text[], 12.12000, -86.25000, NULL, false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Centro Nacional de Endoscopía - Hospital Alemán Nicaragüense', 'CENTRO_SALUD', 'Centro Especializado', NULL, NULL, 'Managua', NULL, 'Urbano', ARRAY['Gastroenterología','Endoscopía']::text[], 12.13300, -86.28500, NULL, false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Centro Oftalmológico Sandino', 'CENTRO_SALUD', 'Centro Especializado', NULL, NULL, 'Managua', NULL, 'Urbano', ARRAY['Oftalmología']::text[], 12.13000, -86.27000, NULL, false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Centro Oncológico de Quimioterapias y Cuidados Paliativos', 'CENTRO_SALUD', 'Centro Especializado', NULL, NULL, 'Managua', NULL, 'Urbano', ARRAY['Oncología','Quimioterapia','Cuidados paliativos']::text[], 12.12500, -86.28000, NULL, false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Centro de Salud Roberto Herrera Ríos', 'CENTRO_SALUD', 'Centro de Salud', NULL, 'D1', 'Managua', 'De Transnica 2c al Lago Reparto Serrano', 'Urbano', ARRAY['Atención general','Vacunación','Pediatría']::text[], 12.13500, -86.24500, 'De Transnica 2c al Lago Reparto Serrano', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Centro de Salud Francisco Morazán', 'CENTRO_SALUD', 'Centro de Salud', NULL, 'D2', 'Managua', 'Colonia Francisco Morazán', 'Urbano', ARRAY['Atención general','Vacunación','Pediatría']::text[], 12.14000, -86.29500, 'Colonia Francisco Morazán', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Centro de Salud Sócrates Flórez', 'CENTRO_SALUD', 'Centro de Salud', NULL, 'D2', 'Managua', 'Portón del Cementerio General 2c al Norte Santa Ana Sur', 'Urbano', ARRAY['Atención general','Vacunación','Pediatría']::text[], 12.13800, -86.29000, 'Portón del Cementerio General 2c al Norte Santa Ana Sur', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Centro de Salud Altagracia', 'CENTRO_SALUD', 'Centro de Salud', NULL, 'D3', 'Managua', 'B Altagracia Frente a Costado Sur Policía Nacional D3', 'Urbano', ARRAY['Atención general','Vacunación','Pediatría']::text[], 12.12000, -86.29000, 'B Altagracia Frente a Costado Sur Policía Nacional D3', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Centro de Salud Edgar Lang', 'CENTRO_SALUD', 'Centro de Salud', NULL, 'D3', 'Managua', 'Bo San Judas Contiguo al Mercado', 'Urbano', ARRAY['Atención general','Vacunación','Pediatría']::text[], 12.11800, -86.28500, 'Bo San Judas Contiguo al Mercado', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Centro de Salud Francisco Buitrago', 'CENTRO_SALUD', 'Centro de Salud', NULL, 'D4', 'Managua', 'Bo San Luis Sur detrás del Catastro frente CECNA', 'Urbano', ARRAY['Atención general','Vacunación','Pediatría']::text[], 12.11500, -86.27500, 'Bo San Luis Sur detrás del Catastro frente CECNA', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Centro de Salud Carlos Rugama', 'CENTRO_SALUD', 'Centro de Salud', NULL, 'D5', 'Managua', 'De la Duya Mágica 1c al sur 1c abajo Walter Ferrety', 'Urbano', ARRAY['Atención general','Vacunación','Pediatría']::text[], 12.12000, -86.23500, 'De la Duya Mágica 1c al sur 1c abajo Walter Ferrety', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Centro de Salud Pedro Altamirano', 'CENTRO_SALUD', 'Centro de Salud', NULL, 'D5', 'Managua', 'Detrás del Mercado Roberto Huembes Carlos Fonseca', 'Urbano', ARRAY['Atención general','Vacunación','Pediatría']::text[], 12.12100, -86.24500, 'Detrás del Mercado Roberto Huembes Carlos Fonseca', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Centro de Salud Silvia Ferrufino', 'CENTRO_SALUD', 'Centro de Salud', NULL, 'D6', 'Managua', 'Carretera Norte Gasolinera Uno Waspan 1 cuadra al Norte Jorge Casaly', 'Urbano', ARRAY['Atención general','Vacunación','Pediatría']::text[], 12.15000, -86.27000, 'Carretera Norte Gasolinera Uno Waspan 1 cuadra al Norte Jorge Casaly', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Centro de Salud Roger Osorio', 'CENTRO_SALUD', 'Centro de Salud', NULL, 'D6', 'Managua', 'Américas 2 Fte Colegio José Benito Escobar Villa José Benito Escobar', 'Urbano', ARRAY['Atención general','Vacunación','Pediatría']::text[], 12.14500, -86.26500, 'Américas 2 Fte Colegio José Benito Escobar Villa José Benito Escobar', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Centro de Salud Jesús Zamora González', 'CENTRO_SALUD', 'Centro de Salud', NULL, 'D6', 'Managua', 'Pista Principal Sabanagrande al Tope ciudadela Ciudadela Belén', 'Urbano', ARRAY['Atención general','Vacunación','Pediatría']::text[], 12.15500, -86.26000, 'Pista Principal Sabanagrande al Tope ciudadela Ciudadela Belén', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Centro de Salud Villa Libertad', 'CENTRO_SALUD', 'Centro de Salud', NULL, 'D7', 'Managua', 'Frente a los pozos de ENACAL Villa Libertad', 'Urbano', ARRAY['Atención general','Vacunación','Pediatría']::text[], 12.14000, -86.25500, 'Frente a los pozos de ENACAL Villa Libertad', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Centro de Salud Iraní', 'CENTRO_SALUD', 'Centro de Salud', NULL, 'D7', 'Managua', 'Villa Libertad casa comunal 1c al sur', 'Urbano', ARRAY['Atención general','Vacunación','Pediatría']::text[], 12.13900, -86.25400, 'Villa Libertad casa comunal 1c al sur', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Puesto de Salud Georgino Andrade', 'PUESTO_MEDICO', 'Puesto de Salud', NULL, NULL, 'Managua', 'Costado oeste del parque Bo Georgino Andrade', 'Urbano', ARRAY['Atención general básica','Vacunación','Curaciones']::text[], 12.13000, -86.26500, 'Costado oeste del parque Bo Georgino Andrade', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Puesto de Salud Enrique Smith', 'PUESTO_MEDICO', 'Puesto de Salud', NULL, NULL, 'Managua', 'Entrada principal 1 cuadra al sur media arriba Bo Enrique Smith', 'Urbano', ARRAY['Atención general básica','Vacunación','Curaciones']::text[], 12.12800, -86.26000, 'Entrada principal 1 cuadra al sur media arriba Bo Enrique Smith', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Puesto de Salud Che Guevara (Laureles Sur)', 'PUESTO_MEDICO', 'Puesto de Salud', NULL, NULL, 'Managua', 'Bo Laureles Sur Terminal Ruta 168', 'Urbano', ARRAY['Atención general básica','Vacunación','Curaciones']::text[], 12.13200, -86.27000, 'Bo Laureles Sur Terminal Ruta 168', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Puesto de Salud Arlen Siú', 'PUESTO_MEDICO', 'Puesto de Salud', NULL, NULL, 'Managua', 'Casa Comunal del Barrio Arlen Siú', 'Urbano', ARRAY['Atención general básica','Vacunación','Curaciones']::text[], 12.12500, -86.25500, 'Casa Comunal del Barrio Arlen Siú', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Puesto de Salud Américas 1', 'PUESTO_MEDICO', 'Puesto de Salud', NULL, NULL, 'Managua', 'Américas 1 contiguo a CDI Sol de Libertad', 'Urbano', ARRAY['Atención general básica','Vacunación','Curaciones']::text[], 12.14500, -86.26000, 'Américas 1 contiguo a CDI Sol de Libertad', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Puesto de Salud 1ro de Mayo', 'PUESTO_MEDICO', 'Puesto de Salud', NULL, NULL, 'Managua', 'Costado Sur Este del CNDR Primero de Mayo', 'Urbano', ARRAY['Atención general básica','Vacunación','Curaciones']::text[], 12.11900, -86.25100, 'Costado Sur Este del CNDR Primero de Mayo', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Puesto de Salud Villa Israel', 'PUESTO_MEDICO', 'Puesto de Salud', NULL, NULL, 'Managua', 'Bo Villa Israel Entrada del Mercado Mayoreo 3c arriba', 'Urbano', ARRAY['Atención general básica','Vacunación','Curaciones']::text[], 12.12500, -86.29500, 'Bo Villa Israel Entrada del Mercado Mayoreo 3c arriba', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Puesto de Salud Villa Dignidad', 'PUESTO_MEDICO', 'Puesto de Salud', NULL, NULL, 'Managua', 'Los Rieles 1 1/2 al norte', 'Urbano', ARRAY['Atención general básica','Vacunación','Curaciones']::text[], 12.12000, -86.30000, 'Los Rieles 1 1/2 al norte', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Puesto de Salud Reparto Segovia', 'PUESTO_MEDICO', 'Puesto de Salud', NULL, NULL, 'Managua', 'Donde fue la Ferretería 4 4c arriba', 'Urbano', ARRAY['Atención general básica','Vacunación','Curaciones']::text[], 12.13500, -86.26000, 'Donde fue la Ferretería 4 4c arriba', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Puesto de Salud La Esperanza (Berta Díaz)', 'PUESTO_MEDICO', 'Puesto de Salud', NULL, NULL, 'Managua', 'Foto Técnica 2c al lago 1c abajo 1c al lago 110 vrs arriba', 'Urbano', ARRAY['Atención general básica','Vacunación','Curaciones']::text[], 12.13000, -86.25000, 'Foto Técnica 2c al lago 1c abajo 1c al lago 110 vrs arriba', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Puesto de Salud Conmema', 'PUESTO_MEDICO', 'Puesto de Salud', NULL, NULL, 'Managua', 'Instalaciones de Conmema Mercado Mayoreo Barrio Concepción de María', 'Urbano', ARRAY['Atención general básica','Vacunación','Curaciones']::text[], 12.12600, -86.29000, 'Instalaciones de Conmema Mercado Mayoreo Barrio Concepción de María', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Puesto de Salud Camilo Chamorro', 'PUESTO_MEDICO', 'Puesto de Salud', NULL, NULL, 'Managua', 'Rocargo 2c al lago 1 1/2 abajo a mano izquierda', 'Urbano', ARRAY['Atención general básica','Vacunación','Curaciones']::text[], 12.13300, -86.25500, 'Rocargo 2c al lago 1 1/2 abajo a mano izquierda', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Puesto de Salud Waspan Sur', 'PUESTO_MEDICO', 'Puesto de Salud', NULL, NULL, 'Managua', 'Donde fue La Maber Carretera Norte 3 cuadra al Sur 1 al este', 'Urbano', ARRAY['Atención general básica','Vacunación','Curaciones']::text[], 12.14800, -86.27200, 'Donde fue La Maber Carretera Norte 3 cuadra al Sur 1 al este', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Puesto de Salud Villa Reconciliación Sur', 'PUESTO_MEDICO', 'Puesto de Salud', NULL, NULL, 'Managua', 'Gasolinera 2 de Agosto PETRONIC 2c abajo 1c al lago', 'Urbano', ARRAY['Atención general básica','Vacunación','Curaciones']::text[], 12.14300, -86.26500, 'Gasolinera 2 de Agosto PETRONIC 2c abajo 1c al lago', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Puesto de Salud Casa España (San Antonio Sur)', 'PUESTO_MEDICO', 'Puesto de Salud', NULL, NULL, 'Managua', 'Comarca SAS Club Casa España', 'Urbano', ARRAY['Atención general básica','Vacunación','Curaciones']::text[], 12.13800, -86.25000, 'Comarca SAS Club Casa España', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Puesto de Salud Roberto Clemente', 'PUESTO_MEDICO', 'Puesto de Salud', NULL, NULL, 'Managua', 'Puente La Reynaga 3c al oeste 1½ al sur Bo Larreynaga', 'Urbano', ARRAY['Atención general básica','Vacunación','Curaciones']::text[], 12.12800, -86.24000, 'Puente La Reynaga 3c al oeste 1½ al sur Bo Larreynaga', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Puesto de Salud San José Oriental', 'PUESTO_MEDICO', 'Puesto de Salud', NULL, NULL, 'Managua', 'Bo San José Oriental de la ITR 2c al Sur 1c abajo 1/2 al lago', 'Urbano', ARRAY['Atención general básica','Vacunación','Curaciones']::text[], 12.12200, -86.25000, 'Bo San José Oriental de la ITR 2c al Sur 1c abajo 1/2 al lago', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Puesto de Salud Selim Shible', 'PUESTO_MEDICO', 'Puesto de Salud', NULL, NULL, 'Managua', 'Bo Selim Shible de la Perfecta 2c al lago 1c arriba', 'Urbano', ARRAY['Atención general básica','Vacunación','Curaciones']::text[], 12.13500, -86.25500, 'Bo Selim Shible de la Perfecta 2c al lago 1c arriba', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Puesto de Salud René Polanco', 'PUESTO_MEDICO', 'Puesto de Salud', NULL, NULL, 'Managua', 'De la casa de la mujer 3 cuadra al lago 20 vrs arriba', 'Urbano', ARRAY['Atención general básica','Vacunación','Curaciones']::text[], 12.13200, -86.25800, 'De la casa de la mujer 3 cuadra al lago 20 vrs arriba', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Puesto de Salud Salomón Moreno', 'PUESTO_MEDICO', 'Puesto de Salud', NULL, NULL, 'Managua', 'De donde fue el cine ideal 1 arriba 1 al este', 'Urbano', ARRAY['Atención general básica','Vacunación','Curaciones']::text[], 12.13000, -86.25200, 'De donde fue el cine ideal 1 arriba 1 al este', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Puesto de Salud Esquipulas', 'PUESTO_MEDICO', 'Puesto de Salud', NULL, NULL, 'Managua', 'Frente a la Iglesia Católica Esquipulas', 'Urbano', ARRAY['Atención general básica','Vacunación','Curaciones']::text[], 12.14500, -86.25000, 'Frente a la Iglesia Católica Esquipulas', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Puesto de Salud Villa Miguel Gutiérrez', 'PUESTO_MEDICO', 'Puesto de Salud', NULL, NULL, 'Managua', 'Semaforos de la Villa Miguel Gutiérrez 1 cuadra al norte 1 al este', 'Urbano', ARRAY['Atención general básica','Vacunación','Curaciones']::text[], 12.14200, -86.25500, 'Semaforos de la Villa Miguel Gutiérrez 1 cuadra al norte 1 al este', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Puesto de Salud La Primavera', 'PUESTO_MEDICO', 'Puesto de Salud', NULL, NULL, 'Managua', 'Carretera Norte Donde fue la Simen 12 cuadra al lago', 'Urbano', ARRAY['Atención general básica','Vacunación','Curaciones']::text[], 12.15500, -86.26500, 'Carretera Norte Donde fue la Simen 12 cuadra al lago', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Puesto de Salud José Dolores Estrada', 'PUESTO_MEDICO', 'Puesto de Salud', NULL, NULL, 'Managua', 'Carretera Norte Donde fue la Maber 5 cuadra al norte', 'Urbano', ARRAY['Atención general básica','Vacunación','Curaciones']::text[], 12.15200, -86.27000, 'Carretera Norte Donde fue la Maber 5 cuadra al norte', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Puesto de Salud Sabana Grande', 'PUESTO_MEDICO', 'Puesto de Salud', NULL, NULL, 'Managua', 'Cruces de los rieles 3 cuadras arriba a mano izquierda', 'Urbano', ARRAY['Atención general básica','Vacunación','Curaciones']::text[], 12.15000, -86.26200, 'Cruces de los rieles 3 cuadras arriba a mano izquierda', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Puesto de Salud San Sebastián', 'PUESTO_MEDICO', 'Puesto de Salud', NULL, NULL, 'Managua', 'Bo San Sebastián Cine Blanco 4c arriba', 'Urbano', ARRAY['Atención general básica','Vacunación','Curaciones']::text[], 12.12500, -86.24000, 'Bo San Sebastián Cine Blanco 4c arriba', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Puesto de Salud Memorial Sandino', 'PUESTO_MEDICO', 'Puesto de Salud', NULL, NULL, 'Managua', 'Bo Memorial Sandino frente a la Cancha', 'Urbano', ARRAY['Atención general básica','Vacunación','Curaciones']::text[], 12.12000, -86.23500, 'Bo Memorial Sandino frente a la Cancha', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Policlínico Adulto Mayor Lidia Saavedra de Ortega', 'CLINICA', 'Clínica Previsional', NULL, NULL, 'Managua', 'Del Ministerio del Trabajo 2c arriba 2c al lago', 'Urbano', ARRAY['Atención general','Gerontología']::text[], 12.13000, -86.27500, 'Del Ministerio del Trabajo 2c arriba 2c al lago', false);
INSERT INTO public.centros_salud (nombre, tipo, tipo_unidad, silais, distrito, municipio, localidad, zona, especialidades, latitud, longitud, direccion, coordenadas_verificadas) VALUES ('Sub-Filial Zona Franca', 'CLINICA', 'Clínica Previsional', NULL, NULL, 'Managua', 'Carretera Norte Complejo Zona Franca Las Mercedes', 'Urbano', ARRAY['Atención general']::text[], 12.14000, -86.26500, 'Carretera Norte Complejo Zona Franca Las Mercedes', false);

COMMIT;
